language: node_js
node_js:
  - "11.10.1"
services:
  - mysql
before_install:
  - sudo service mysql stop
  - sudo service mysql start
  - mysql -u root --password="" < ./LabelLab.sql
cache:
  directories:
  - front-end/node_modules
  - back-end/node_modules
before_script:
  - mkdir back-end/public/uploads
script: "bash ./testscript.sh"
