language: node_js
node_js:
  - "11.10.1"
services:
  - mysql
before_install:
  - mysql -u root --password="" < LabelLab.sql
cache:
  directories:
  - front-end/node_modules
  - back-end/node_moduless
script: "./testscript.sh"
